### ISSUE TITLE
希望可以添加自定义请求头

### ISSUE THREAD

**Issue by jingxiu1016** [agents-flex/agents-flex#5]
一些特定需求下

**Comment by yangfuhai** [comment]
不明白你说的是哪个地方

**Comment by jingxiu1016** [comment]
> 不明白你说的是哪个地方
![image](https://github.com/user-attachments/assets/bb269552-5762-4cf3-94be-1a150b440f6f)

就是在chat 后者 chatStream 方法中的这个部分，我想从外部添加一个请求头信息没有办法

我当然可以自己去实现一个LLM，但只是为了添加一个请求头就稍显麻烦了些
